"""empty message

Revision ID: 4dab81aef8ce
Revises: 
Create Date: 2023-08-02 14:55:16.848515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dab81aef8ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geonames',
    sa.Column('geonameid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('asciiname', sa.String(), nullable=True),
    sa.Column('alternatenames', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('feature_class', sa.String(), nullable=True),
    sa.Column('feature_code', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('cc2', sa.String(), nullable=True),
    sa.Column('admin1_code', sa.String(), nullable=True),
    sa.Column('admin2_code', sa.String(), nullable=True),
    sa.Column('admin3_code', sa.String(), nullable=True),
    sa.Column('admin4_code', sa.String(), nullable=True),
    sa.Column('population', sa.String(), nullable=True),
    sa.Column('elevation', sa.String(), nullable=True),
    sa.Column('dem', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('modification_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('geonameid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geonames')
    # ### end Alembic commands ###
